// this script pulls ALL (2909) tickers in one go
// this script returns the isin codes
import axios from 'axios';
import fs from 'fs';
import path from 'path';

// get dirname of this file

const main = async () => {
  const response = await axios.post(
    'https://www.justetf.com/en/search.html?2-1.0-container-tabsContentContainer-tabsContentRepeater-1-container-content-etfsTablePanel&search=ETFS&_wicket=1&_wicket=1',
    new URLSearchParams({
      draw: '1',
      'columns[0][data]': '',
      'columns[0][name]': 'selectCheckbox',
      'columns[0][searchable]': 'true',
      'columns[0][orderable]': 'false',
      'columns[0][search][value]': '',
      'columns[0][search][regex]': 'false',
      'columns[1][data]': 'name',
      'columns[1][name]': 'name',
      'columns[1][searchable]': 'true',
      'columns[1][orderable]': 'true',
      'columns[1][search][value]': '',
      'columns[1][search][regex]': 'false',
      'columns[2][data]': '',
      'columns[2][name]': 'sparkline',
      'columns[2][searchable]': 'true',
      'columns[2][orderable]': 'false',
      'columns[2][search][value]': '',
      'columns[2][search][regex]': 'false',
      'columns[3][data]': 'fundCurrency',
      'columns[3][name]': 'fundCurrency',
      'columns[3][searchable]': 'true',
      'columns[3][orderable]': 'true',
      'columns[3][search][value]': '',
      'columns[3][search][regex]': 'false',
      'columns[4][data]': 'fundSize',
      'columns[4][name]': 'fundSize',
      'columns[4][searchable]': 'true',
      'columns[4][orderable]': 'true',
      'columns[4][search][value]': '',
      'columns[4][search][regex]': 'false',
      'columns[5][data]': 'ter',
      'columns[5][name]': 'ter',
      'columns[5][searchable]': 'true',
      'columns[5][orderable]': 'true',
      'columns[5][search][value]': '',
      'columns[5][search][regex]': 'false',
      'columns[6][data]': '',
      'columns[6][name]': 'bullet',
      'columns[6][searchable]': 'true',
      'columns[6][orderable]': 'false',
      'columns[6][search][value]': '',
      'columns[6][search][regex]': 'false',
      'columns[7][data]': 'weekReturnCUR',
      'columns[7][name]': 'weekReturn',
      'columns[7][searchable]': 'true',
      'columns[7][orderable]': 'true',
      'columns[7][search][value]': '',
      'columns[7][search][regex]': 'false',
      'columns[8][data]': 'monthReturnCUR',
      'columns[8][name]': 'monthReturn',
      'columns[8][searchable]': 'true',
      'columns[8][orderable]': 'true',
      'columns[8][search][value]': '',
      'columns[8][search][regex]': 'false',
      'columns[9][data]': 'threeMonthReturnCUR',
      'columns[9][name]': 'threeMonthReturn',
      'columns[9][searchable]': 'true',
      'columns[9][orderable]': 'true',
      'columns[9][search][value]': '',
      'columns[9][search][regex]': 'false',
      'columns[10][data]': 'sixMonthReturnCUR',
      'columns[10][name]': 'sixMonthReturn',
      'columns[10][searchable]': 'true',
      'columns[10][orderable]': 'true',
      'columns[10][search][value]': '',
      'columns[10][search][regex]': 'false',
      'columns[11][data]': 'yearReturnCUR',
      'columns[11][name]': 'yearReturn',
      'columns[11][searchable]': 'true',
      'columns[11][orderable]': 'true',
      'columns[11][search][value]': '',
      'columns[11][search][regex]': 'false',
      'columns[12][data]': 'threeYearReturnCUR',
      'columns[12][name]': 'threeYearReturn',
      'columns[12][searchable]': 'true',
      'columns[12][orderable]': 'true',
      'columns[12][search][value]': '',
      'columns[12][search][regex]': 'false',
      'columns[13][data]': 'fiveYearReturnCUR',
      'columns[13][name]': 'fiveYearReturn',
      'columns[13][searchable]': 'true',
      'columns[13][orderable]': 'true',
      'columns[13][search][value]': '',
      'columns[13][search][regex]': 'false',
      'columns[14][data]': 'ytdReturnCUR',
      'columns[14][name]': 'ytdReturn',
      'columns[14][searchable]': 'true',
      'columns[14][orderable]': 'true',
      'columns[14][search][value]': '',
      'columns[14][search][regex]': 'false',
      'columns[15][data]': 'yearReturn1CUR',
      'columns[15][name]': 'yearReturn1',
      'columns[15][searchable]': 'true',
      'columns[15][orderable]': 'true',
      'columns[15][search][value]': '',
      'columns[15][search][regex]': 'false',
      'columns[16][data]': 'yearReturn2CUR',
      'columns[16][name]': 'yearReturn2',
      'columns[16][searchable]': 'true',
      'columns[16][orderable]': 'true',
      'columns[16][search][value]': '',
      'columns[16][search][regex]': 'false',
      'columns[17][data]': 'yearReturn3CUR',
      'columns[17][name]': 'yearReturn3',
      'columns[17][searchable]': 'true',
      'columns[17][orderable]': 'true',
      'columns[17][search][value]': '',
      'columns[17][search][regex]': 'false',
      'columns[18][data]': 'yearReturn4CUR',
      'columns[18][name]': 'yearReturn4',
      'columns[18][searchable]': 'true',
      'columns[18][orderable]': 'true',
      'columns[18][search][value]': '',
      'columns[18][search][regex]': 'false',
      'columns[19][data]': 'yearVolatilityCUR',
      'columns[19][name]': 'yearVolatility',
      'columns[19][searchable]': 'true',
      'columns[19][orderable]': 'true',
      'columns[19][search][value]': '',
      'columns[19][search][regex]': 'false',
      'columns[20][data]': 'threeYearVolatilityCUR',
      'columns[20][name]': 'threeYearVolatility',
      'columns[20][searchable]': 'true',
      'columns[20][orderable]': 'true',
      'columns[20][search][value]': '',
      'columns[20][search][regex]': 'false',
      'columns[21][data]': 'fiveYearVolatilityCUR',
      'columns[21][name]': 'fiveYearVolatility',
      'columns[21][searchable]': 'true',
      'columns[21][orderable]': 'true',
      'columns[21][search][value]': '',
      'columns[21][search][regex]': 'false',
      'columns[22][data]': 'yearReturnPerRiskCUR',
      'columns[22][name]': 'yearReturnPerRisk',
      'columns[22][searchable]': 'true',
      'columns[22][orderable]': 'true',
      'columns[22][search][value]': '',
      'columns[22][search][regex]': 'false',
      'columns[23][data]': 'threeYearReturnPerRiskCUR',
      'columns[23][name]': 'threeYearReturnPerRisk',
      'columns[23][searchable]': 'true',
      'columns[23][orderable]': 'true',
      'columns[23][search][value]': '',
      'columns[23][search][regex]': 'false',
      'columns[24][data]': 'fiveYearReturnPerRiskCUR',
      'columns[24][name]': 'fiveYearReturnPerRisk',
      'columns[24][searchable]': 'true',
      'columns[24][orderable]': 'true',
      'columns[24][search][value]': '',
      'columns[24][search][regex]': 'false',
      'columns[25][data]': 'yearMaxDrawdownCUR',
      'columns[25][name]': 'yearMaxDrawdown',
      'columns[25][searchable]': 'true',
      'columns[25][orderable]': 'true',
      'columns[25][search][value]': '',
      'columns[25][search][regex]': 'false',
      'columns[26][data]': 'threeYearMaxDrawdownCUR',
      'columns[26][name]': 'threeYearMaxDrawdown',
      'columns[26][searchable]': 'true',
      'columns[26][orderable]': 'true',
      'columns[26][search][value]': '',
      'columns[26][search][regex]': 'false',
      'columns[27][data]': 'fiveYearMaxDrawdownCUR',
      'columns[27][name]': 'fiveYearMaxDrawdown',
      'columns[27][searchable]': 'true',
      'columns[27][orderable]': 'true',
      'columns[27][search][value]': '',
      'columns[27][search][regex]': 'false',
      'columns[28][data]': 'maxDrawdownCUR',
      'columns[28][name]': 'maxDrawdown',
      'columns[28][searchable]': 'true',
      'columns[28][orderable]': 'true',
      'columns[28][search][value]': '',
      'columns[28][search][regex]': 'false',
      'columns[29][data]': 'inceptionDate',
      'columns[29][name]': 'inceptionDate',
      'columns[29][searchable]': 'true',
      'columns[29][orderable]': 'true',
      'columns[29][search][value]': '',
      'columns[29][search][regex]': 'false',
      'columns[30][data]': 'distributionPolicy',
      'columns[30][name]': 'distributionPolicy',
      'columns[30][searchable]': 'true',
      'columns[30][orderable]': 'false',
      'columns[30][search][value]': '',
      'columns[30][search][regex]': 'false',
      'columns[31][data]': 'sustainable',
      'columns[31][name]': 'sustainable',
      'columns[31][searchable]': 'true',
      'columns[31][orderable]': 'true',
      'columns[31][search][value]': '',
      'columns[31][search][regex]': 'false',
      'columns[32][data]': 'numberOfHoldings',
      'columns[32][name]': 'numberOfHoldings',
      'columns[32][searchable]': 'true',
      'columns[32][orderable]': 'true',
      'columns[32][search][value]': '',
      'columns[32][search][regex]': 'false',
      'columns[33][data]': 'currentDividendYield',
      'columns[33][name]': 'currentDividendYield',
      'columns[33][searchable]': 'true',
      'columns[33][orderable]': 'true',
      'columns[33][search][value]': '',
      'columns[33][search][regex]': 'false',
      'columns[34][data]': 'yearDividendYield',
      'columns[34][name]': 'yearDividendYield',
      'columns[34][searchable]': 'true',
      'columns[34][orderable]': 'true',
      'columns[34][search][value]': '',
      'columns[34][search][regex]': 'false',
      'columns[35][data]': 'domicileCountry',
      'columns[35][name]': 'domicileCountry',
      'columns[35][searchable]': 'true',
      'columns[35][orderable]': 'false',
      'columns[35][search][value]': '',
      'columns[35][search][regex]': 'false',
      'columns[36][data]': 'replicationMethod',
      'columns[36][name]': 'replicationMethod',
      'columns[36][searchable]': 'true',
      'columns[36][orderable]': 'false',
      'columns[36][search][value]': '',
      'columns[36][search][regex]': 'false',
      'columns[37][data]': 'savingsPlanReady',
      'columns[37][name]': 'savingsPlanReady',
      'columns[37][searchable]': 'true',
      'columns[37][orderable]': 'false',
      'columns[37][search][value]': '',
      'columns[37][search][regex]': 'false',
      'columns[38][data]': 'hasSecuritiesLending',
      'columns[38][name]': 'hasSecuritiesLending',
      'columns[38][searchable]': 'true',
      'columns[38][orderable]': 'false',
      'columns[38][search][value]': '',
      'columns[38][search][regex]': 'false',
      'columns[39][data]': 'isin',
      'columns[39][name]': 'isin',
      'columns[39][searchable]': 'true',
      'columns[39][orderable]': 'false',
      'columns[39][search][value]': '',
      'columns[39][search][regex]': 'false',
      'columns[40][data]': 'ticker',
      'columns[40][name]': 'ticker',
      'columns[40][searchable]': 'true',
      'columns[40][orderable]': 'false',
      'columns[40][search][value]': '',
      'columns[40][search][regex]': 'false',
      'columns[41][data]': 'wkn',
      'columns[41][name]': 'wkn',
      'columns[41][searchable]': 'true',
      'columns[41][orderable]': 'false',
      'columns[41][search][value]': '',
      'columns[41][search][regex]': 'false',
      'columns[42][data]': 'valorNumber',
      'columns[42][name]': 'valorNumber',
      'columns[42][searchable]': 'true',
      'columns[42][orderable]': 'false',
      'columns[42][search][value]': '',
      'columns[42][search][regex]': 'false',
      'columns[43][data]': '',
      'columns[43][name]': 'addButton',
      'columns[43][searchable]': 'true',
      'columns[43][orderable]': 'false',
      'columns[43][search][value]': '',
      'columns[43][search][regex]': 'false',
      'order[0][column]': '4',
      'order[0][dir]': 'desc',
      start: '0',
      length: '3200',
      'search[value]': '',
      'search[regex]': 'false',
      ajaxsortOrder: 'desc',
      ajaxsortField: 'fundSize',
      lang: 'en',
      country: 'DE',
      defaultCurrency: 'EUR',
      universeType: 'private',
      etfsParams: 'search=ETFS&_wicket=1&query=',
    }),
    {
      headers: {
        accept: 'application/json, text/javascript, */*; q=0.01',
        'accept-language': 'en-US,en;q=0.9',
        'cache-control': 'no-cache',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        origin: 'https://www.justetf.com',
        pragma: 'no-cache',
        priority: 'u=1, i',
        referer:
          'https://www.justetf.com/en/search.html?12-1.0-container-tabsContentContainer-tabsContentRepeater-1-container-content-etfsTablePanel&search=ETFS&_wicket=1',
        'sec-ch-ua':
          '"Microsoft Edge";v="137", "Chromium";v="137", "Not/A)Brand";v="24"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'user-agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0',
        'x-requested-with': 'XMLHttpRequest',
        cookie:
          'priceAlertdontShowAgain=false; CookieConsent={stamp:%277mUnCfvnpc5YvGVQa5PgUgs6+xcFUvhkiDW/tYp2A4UxbRsHZOKZoA==%27%2Cnecessary:true%2Cpreferences:false%2Cstatistics:false%2Cmarketing:false%2Cmethod:%27explicit%27%2Cver:7%2Cutc:1750680410670%2Cregion:%27za%27}; etfs-search-order=fundSize%2Cdesc; p=281180; pRef=TTbeginner*GB*en*LP*INDEXEN; XSRF-TOKEN=25450619-6fed-467b-871e-2961f4cb32d2; JSESSIONID=5B8349A9AEC0876EE24C5619515A7D39; locale_=en; AWSALB=AP1pzmC2zXuBJf4x6XX+E0jHzg+TVtWFuqFdpkcq7zG5+Ua3zZVSPrHVHKRuQJ0s54qSvQHYVlj2e3gN00rL3t1IJouOiowO6r5k7opskPpIthn6gZoJQcevaMiP; AWSALBCORS=AP1pzmC2zXuBJf4x6XX+E0jHzg+TVtWFuqFdpkcq7zG5+Ua3zZVSPrHVHKRuQJ0s54qSvQHYVlj2e3gN00rL3t1IJouOiowO6r5k7opskPpIthn6gZoJQcevaMiP',
      },
    },
  );

  const __dirname = process.cwd();

  // write the response to a file in same directory
  const filePath = path.join(__dirname, 'justetf2.json');
  fs.writeFileSync(filePath, JSON.stringify(response.data, null, 2), 'utf-8');

  // write to json file in this dir
};

main();
